export const SLOT_LIST_REQUEST = 'SLOT_LIST_REQUEST';
export const SLOT_LIST_SUCCESS = 'SLOT_LIST_SUCCESS';
export const SLOT_LIST_FAIL = 'SLOT_LIST_FAIL';

// SLOT DETAILS CONSTANTS
export const SLOT_DETAILS_REQUEST = 'SLOT_DETAILS_REQUEST';
export const SLOT_DETAILS_SUCCESS = 'SLOT_DETAILS_SUCCESS';
export const SLOT_DETAILS_FAIL = 'SLOT_DETAILS_FAIL';

// CREATE NEW SLOT CONSTANTS
export const SLOT_UPDATE_REQUEST = 'SLOT_UPDATE_REQUEST';
export const SLOT_UPDATE_SUCCESS = 'SLOT_UPDATE_SUCCESS';
export const SLOT_UPDATE_FAIL = 'SLOT_UPDATE_FAIL';
export const SLOT_UPDATE_RESET = 'SLOT_UPDATE_RESET';
